[package]
name = "prismup"
version = "0.1.0"
edition = "2024"
authors = ["Michel Boucey <michel.boucey@gmail.com>"]
license = "BSD-3-Clause"
categories = ["command-line-utilities"]
description = "A Prism language installer"
homepage = "https://github.com/MichelBoucey/prismup"
repository = "https://github.com/MichelBoucey/prismup"
readme = "README.md"
keywords = ["prism", "language", "cli"]

[dependencies]
semver = "1.0.28"
regex = "1.13.0"
tokio = { version = "1", features = ["full"] }
exponential-backoff = "2.1.0"
reqwest = { version = "0.13", features = ["stream"] }
sha256 = "1.6.0"
clap = "4.6.2"
flate2 = "1.1.9"
tar = "0.4.46"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
futures-util = "0.3.32"
colored = "3.1.1"
